// Copyright 2026 Naadir Jeewa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: stage/stage.proto

package stage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoRequest) Reset() {
	*x = PluginInfoRequest{}
	mi := &file_stage_stage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoRequest) ProtoMessage() {}

func (x *PluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoRequest.ProtoReflect.Descriptor instead.
func (*PluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{0}
}

type PluginInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the plugin identifier (e.g. "nvmet", "nfs").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// vendor_version of the plugin binary.
	VendorVersion string `protobuf:"bytes,2,opt,name=vendor_version,json=vendorVersion,proto3" json:"vendor_version,omitempty"`
	// manifest of optional opaque metadata.
	Manifest      map[string]string `protobuf:"bytes,3,rep,name=manifest,proto3" json:"manifest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoResponse) Reset() {
	*x = PluginInfoResponse{}
	mi := &file_stage_stage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoResponse) ProtoMessage() {}

func (x *PluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoResponse.ProtoReflect.Descriptor instead.
func (*PluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfoResponse) GetVendorVersion() string {
	if x != nil {
		return x.VendorVersion
	}
	return ""
}

func (x *PluginInfoResponse) GetManifest() map[string]string {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type NodeStageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// staging_path is the CSI staging_target_path (the mount target).
	StagingPath string `protobuf:"bytes,1,opt,name=staging_path,json=stagingPath,proto3" json:"staging_path,omitempty"`
	// fs_type for block sources (ext4|xfs|nfs4). Empty = plugin default.
	FsType string `protobuf:"bytes,2,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	// mount_flags are extra mount options.
	MountFlags []string `protobuf:"bytes,3,rep,name=mount_flags,json=mountFlags,proto3" json:"mount_flags,omitempty"`
	// read_only mounts the staging path read-only.
	ReadOnly bool `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// block requests raw-block staging: the plugin attaches the device and binds
	// the /dev node onto staging_path (a regular file), skipping format + fs
	// mount. fs_type is ignored when block is true.
	Block bool `protobuf:"varint,5,opt,name=block,proto3" json:"block,omitempty"`
	// source is the backing-device union. Exactly one variant per request.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*NodeStageRequest_Nvme
	//	*NodeStageRequest_Device
	//	*NodeStageRequest_Nfs
	Source        isNodeStageRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStageRequest) Reset() {
	*x = NodeStageRequest{}
	mi := &file_stage_stage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStageRequest) ProtoMessage() {}

func (x *NodeStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStageRequest.ProtoReflect.Descriptor instead.
func (*NodeStageRequest) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{2}
}

func (x *NodeStageRequest) GetStagingPath() string {
	if x != nil {
		return x.StagingPath
	}
	return ""
}

func (x *NodeStageRequest) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *NodeStageRequest) GetMountFlags() []string {
	if x != nil {
		return x.MountFlags
	}
	return nil
}

func (x *NodeStageRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *NodeStageRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

func (x *NodeStageRequest) GetSource() isNodeStageRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *NodeStageRequest) GetNvme() *NVMeSource {
	if x != nil {
		if x, ok := x.Source.(*NodeStageRequest_Nvme); ok {
			return x.Nvme
		}
	}
	return nil
}

func (x *NodeStageRequest) GetDevice() *DeviceSource {
	if x != nil {
		if x, ok := x.Source.(*NodeStageRequest_Device); ok {
			return x.Device
		}
	}
	return nil
}

func (x *NodeStageRequest) GetNfs() *NFSSource {
	if x != nil {
		if x, ok := x.Source.(*NodeStageRequest_Nfs); ok {
			return x.Nfs
		}
	}
	return nil
}

type isNodeStageRequest_Source interface {
	isNodeStageRequest_Source()
}

type NodeStageRequest_Nvme struct {
	Nvme *NVMeSource `protobuf:"bytes,10,opt,name=nvme,proto3,oneof"`
}

type NodeStageRequest_Device struct {
	Device *DeviceSource `protobuf:"bytes,11,opt,name=device,proto3,oneof"`
}

type NodeStageRequest_Nfs struct {
	Nfs *NFSSource `protobuf:"bytes,12,opt,name=nfs,proto3,oneof"`
}

func (*NodeStageRequest_Nvme) isNodeStageRequest_Source() {}

func (*NodeStageRequest_Device) isNodeStageRequest_Source() {}

func (*NodeStageRequest_Nfs) isNodeStageRequest_Source() {}

// NVMeSource drives an nvme-tcp attach (transport.Client.Attach) before format +
// mount. Fields mirror transport.TargetRef + the initiator id.
type NVMeSource struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TargetNqn   string                 `protobuf:"bytes,1,opt,name=target_nqn,json=targetNqn,proto3" json:"target_nqn,omitempty"`
	Portal      string                 `protobuf:"bytes,2,opt,name=portal,proto3" json:"portal,omitempty"`
	NamespaceId int32                  `protobuf:"varint,3,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	DeviceGuid  string                 `protobuf:"bytes,4,opt,name=device_guid,json=deviceGuid,proto3" json:"device_guid,omitempty"`
	InitiatorId string                 `protobuf:"bytes,5,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	// tls selects the TLS NVMe/TCP target identified by portal.
	Tls bool `protobuf:"varint,6,opt,name=tls,proto3" json:"tls,omitempty"`
	// psk_secret is the configured Kubernetes Secret NAME only. Stage sidecars
	// may use it for node-local credential delivery; raw PSK material never
	// crosses this RPC.
	PskSecret     string `protobuf:"bytes,7,opt,name=psk_secret,json=pskSecret,proto3" json:"psk_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVMeSource) Reset() {
	*x = NVMeSource{}
	mi := &file_stage_stage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVMeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVMeSource) ProtoMessage() {}

func (x *NVMeSource) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVMeSource.ProtoReflect.Descriptor instead.
func (*NVMeSource) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{3}
}

func (x *NVMeSource) GetTargetNqn() string {
	if x != nil {
		return x.TargetNqn
	}
	return ""
}

func (x *NVMeSource) GetPortal() string {
	if x != nil {
		return x.Portal
	}
	return ""
}

func (x *NVMeSource) GetNamespaceId() int32 {
	if x != nil {
		return x.NamespaceId
	}
	return 0
}

func (x *NVMeSource) GetDeviceGuid() string {
	if x != nil {
		return x.DeviceGuid
	}
	return ""
}

func (x *NVMeSource) GetInitiatorId() string {
	if x != nil {
		return x.InitiatorId
	}
	return ""
}

func (x *NVMeSource) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *NVMeSource) GetPskSecret() string {
	if x != nil {
		return x.PskSecret
	}
	return ""
}

// DeviceSource is a pre-attached raw block device (/dev/rbdX, /dev/mapper/...).
// The plugin skips attach; format + mount only. Generic escape hatch for
// providers that map their own device.
type DeviceSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSource) Reset() {
	*x = DeviceSource{}
	mi := &file_stage_stage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSource) ProtoMessage() {}

func (x *DeviceSource) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSource.ProtoReflect.Descriptor instead.
func (*DeviceSource) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// NFSSource mounts a remote export (server:exportPath). No attach, no format.
type NFSSource struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Server     string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ExportPath string                 `protobuf:"bytes,2,opt,name=export_path,json=exportPath,proto3" json:"export_path,omitempty"`
	// tls selects RFC 9289 mutually-authenticated NFS-over-TLS. The plugin adds xprtsec=mtls and rejects
	// a conflicting caller-supplied xprtsec option.
	Tls           bool `protobuf:"varint,3,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFSSource) Reset() {
	*x = NFSSource{}
	mi := &file_stage_stage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFSSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFSSource) ProtoMessage() {}

func (x *NFSSource) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFSSource.ProtoReflect.Descriptor instead.
func (*NFSSource) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{5}
}

func (x *NFSSource) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *NFSSource) GetExportPath() string {
	if x != nil {
		return x.ExportPath
	}
	return ""
}

func (x *NFSSource) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

type NodeStageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_path is the resolved /dev node for block sources (e.g.
	// /dev/nvme1n1). Empty for nfs.
	DevicePath    string `protobuf:"bytes,1,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStageResponse) Reset() {
	*x = NodeStageResponse{}
	mi := &file_stage_stage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStageResponse) ProtoMessage() {}

func (x *NodeStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStageResponse.ProtoReflect.Descriptor instead.
func (*NodeStageResponse) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{6}
}

func (x *NodeStageResponse) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

type NodeUnstageRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StagingPath string                 `protobuf:"bytes,1,opt,name=staging_path,json=stagingPath,proto3" json:"staging_path,omitempty"`
	// source mirrors NodeStageRequest.source so the plugin knows whether to
	// detach (nvme) or not (device/nfs).
	//
	// Types that are valid to be assigned to Source:
	//
	//	*NodeUnstageRequest_Nvme
	//	*NodeUnstageRequest_Device
	//	*NodeUnstageRequest_Nfs
	Source        isNodeUnstageRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeUnstageRequest) Reset() {
	*x = NodeUnstageRequest{}
	mi := &file_stage_stage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUnstageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUnstageRequest) ProtoMessage() {}

func (x *NodeUnstageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUnstageRequest.ProtoReflect.Descriptor instead.
func (*NodeUnstageRequest) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{7}
}

func (x *NodeUnstageRequest) GetStagingPath() string {
	if x != nil {
		return x.StagingPath
	}
	return ""
}

func (x *NodeUnstageRequest) GetSource() isNodeUnstageRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *NodeUnstageRequest) GetNvme() *NVMeSource {
	if x != nil {
		if x, ok := x.Source.(*NodeUnstageRequest_Nvme); ok {
			return x.Nvme
		}
	}
	return nil
}

func (x *NodeUnstageRequest) GetDevice() *DeviceSource {
	if x != nil {
		if x, ok := x.Source.(*NodeUnstageRequest_Device); ok {
			return x.Device
		}
	}
	return nil
}

func (x *NodeUnstageRequest) GetNfs() *NFSSource {
	if x != nil {
		if x, ok := x.Source.(*NodeUnstageRequest_Nfs); ok {
			return x.Nfs
		}
	}
	return nil
}

type isNodeUnstageRequest_Source interface {
	isNodeUnstageRequest_Source()
}

type NodeUnstageRequest_Nvme struct {
	Nvme *NVMeSource `protobuf:"bytes,10,opt,name=nvme,proto3,oneof"`
}

type NodeUnstageRequest_Device struct {
	Device *DeviceSource `protobuf:"bytes,11,opt,name=device,proto3,oneof"`
}

type NodeUnstageRequest_Nfs struct {
	Nfs *NFSSource `protobuf:"bytes,12,opt,name=nfs,proto3,oneof"`
}

func (*NodeUnstageRequest_Nvme) isNodeUnstageRequest_Source() {}

func (*NodeUnstageRequest_Device) isNodeUnstageRequest_Source() {}

func (*NodeUnstageRequest_Nfs) isNodeUnstageRequest_Source() {}

type NodeUnstageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeUnstageResponse) Reset() {
	*x = NodeUnstageResponse{}
	mi := &file_stage_stage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUnstageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUnstageResponse) ProtoMessage() {}

func (x *NodeUnstageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stage_stage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUnstageResponse.ProtoReflect.Descriptor instead.
func (*NodeUnstageResponse) Descriptor() ([]byte, []int) {
	return file_stage_stage_proto_rawDescGZIP(), []int{8}
}

var File_stage_stage_proto protoreflect.FileDescriptor

const file_stage_stage_proto_rawDesc = "" +
	"\n" +
	"\x11stage/stage.proto\x12\x0estage.v1alpha1\"\x13\n" +
	"\x11PluginInfoRequest\"\xda\x01\n" +
	"\x12PluginInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0evendor_version\x18\x02 \x01(\tR\rvendorVersion\x12L\n" +
	"\bmanifest\x18\x03 \x03(\v20.stage.v1alpha1.PluginInfoResponse.ManifestEntryR\bmanifest\x1a;\n" +
	"\rManifestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x02\n" +
	"\x10NodeStageRequest\x12!\n" +
	"\fstaging_path\x18\x01 \x01(\tR\vstagingPath\x12\x17\n" +
	"\afs_type\x18\x02 \x01(\tR\x06fsType\x12\x1f\n" +
	"\vmount_flags\x18\x03 \x03(\tR\n" +
	"mountFlags\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12\x14\n" +
	"\x05block\x18\x05 \x01(\bR\x05block\x120\n" +
	"\x04nvme\x18\n" +
	" \x01(\v2\x1a.stage.v1alpha1.NVMeSourceH\x00R\x04nvme\x126\n" +
	"\x06device\x18\v \x01(\v2\x1c.stage.v1alpha1.DeviceSourceH\x00R\x06device\x12-\n" +
	"\x03nfs\x18\f \x01(\v2\x19.stage.v1alpha1.NFSSourceH\x00R\x03nfsB\b\n" +
	"\x06source\"\xdb\x01\n" +
	"\n" +
	"NVMeSource\x12\x1d\n" +
	"\n" +
	"target_nqn\x18\x01 \x01(\tR\ttargetNqn\x12\x16\n" +
	"\x06portal\x18\x02 \x01(\tR\x06portal\x12!\n" +
	"\fnamespace_id\x18\x03 \x01(\x05R\vnamespaceId\x12\x1f\n" +
	"\vdevice_guid\x18\x04 \x01(\tR\n" +
	"deviceGuid\x12!\n" +
	"\finitiator_id\x18\x05 \x01(\tR\vinitiatorId\x12\x10\n" +
	"\x03tls\x18\x06 \x01(\bR\x03tls\x12\x1d\n" +
	"\n" +
	"psk_secret\x18\a \x01(\tR\tpskSecret\"\"\n" +
	"\fDeviceSource\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"V\n" +
	"\tNFSSource\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1f\n" +
	"\vexport_path\x18\x02 \x01(\tR\n" +
	"exportPath\x12\x10\n" +
	"\x03tls\x18\x03 \x01(\bR\x03tls\"4\n" +
	"\x11NodeStageResponse\x12\x1f\n" +
	"\vdevice_path\x18\x01 \x01(\tR\n" +
	"devicePath\"\xda\x01\n" +
	"\x12NodeUnstageRequest\x12!\n" +
	"\fstaging_path\x18\x01 \x01(\tR\vstagingPath\x120\n" +
	"\x04nvme\x18\n" +
	" \x01(\v2\x1a.stage.v1alpha1.NVMeSourceH\x00R\x04nvme\x126\n" +
	"\x06device\x18\v \x01(\v2\x1c.stage.v1alpha1.DeviceSourceH\x00R\x06device\x12-\n" +
	"\x03nfs\x18\f \x01(\v2\x19.stage.v1alpha1.NFSSourceH\x00R\x03nfsB\b\n" +
	"\x06source\"\x15\n" +
	"\x13NodeUnstageResponse2\x8c\x02\n" +
	"\vStagePlugin\x12S\n" +
	"\n" +
	"PluginInfo\x12!.stage.v1alpha1.PluginInfoRequest\x1a\".stage.v1alpha1.PluginInfoResponse\x12P\n" +
	"\tNodeStage\x12 .stage.v1alpha1.NodeStageRequest\x1a!.stage.v1alpha1.NodeStageResponse\x12V\n" +
	"\vNodeUnstage\x12\".stage.v1alpha1.NodeUnstageRequest\x1a#.stage.v1alpha1.NodeUnstageResponseB@Z>github.com/randomvariable/zfs-csi/internal/stagepb/stage;stageb\x06proto3"

var (
	file_stage_stage_proto_rawDescOnce sync.Once
	file_stage_stage_proto_rawDescData []byte
)

func file_stage_stage_proto_rawDescGZIP() []byte {
	file_stage_stage_proto_rawDescOnce.Do(func() {
		file_stage_stage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stage_stage_proto_rawDesc), len(file_stage_stage_proto_rawDesc)))
	})
	return file_stage_stage_proto_rawDescData
}

var file_stage_stage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_stage_stage_proto_goTypes = []any{
	(*PluginInfoRequest)(nil),   // 0: stage.v1alpha1.PluginInfoRequest
	(*PluginInfoResponse)(nil),  // 1: stage.v1alpha1.PluginInfoResponse
	(*NodeStageRequest)(nil),    // 2: stage.v1alpha1.NodeStageRequest
	(*NVMeSource)(nil),          // 3: stage.v1alpha1.NVMeSource
	(*DeviceSource)(nil),        // 4: stage.v1alpha1.DeviceSource
	(*NFSSource)(nil),           // 5: stage.v1alpha1.NFSSource
	(*NodeStageResponse)(nil),   // 6: stage.v1alpha1.NodeStageResponse
	(*NodeUnstageRequest)(nil),  // 7: stage.v1alpha1.NodeUnstageRequest
	(*NodeUnstageResponse)(nil), // 8: stage.v1alpha1.NodeUnstageResponse
	nil,                         // 9: stage.v1alpha1.PluginInfoResponse.ManifestEntry
}
var file_stage_stage_proto_depIdxs = []int32{
	9,  // 0: stage.v1alpha1.PluginInfoResponse.manifest:type_name -> stage.v1alpha1.PluginInfoResponse.ManifestEntry
	3,  // 1: stage.v1alpha1.NodeStageRequest.nvme:type_name -> stage.v1alpha1.NVMeSource
	4,  // 2: stage.v1alpha1.NodeStageRequest.device:type_name -> stage.v1alpha1.DeviceSource
	5,  // 3: stage.v1alpha1.NodeStageRequest.nfs:type_name -> stage.v1alpha1.NFSSource
	3,  // 4: stage.v1alpha1.NodeUnstageRequest.nvme:type_name -> stage.v1alpha1.NVMeSource
	4,  // 5: stage.v1alpha1.NodeUnstageRequest.device:type_name -> stage.v1alpha1.DeviceSource
	5,  // 6: stage.v1alpha1.NodeUnstageRequest.nfs:type_name -> stage.v1alpha1.NFSSource
	0,  // 7: stage.v1alpha1.StagePlugin.PluginInfo:input_type -> stage.v1alpha1.PluginInfoRequest
	2,  // 8: stage.v1alpha1.StagePlugin.NodeStage:input_type -> stage.v1alpha1.NodeStageRequest
	7,  // 9: stage.v1alpha1.StagePlugin.NodeUnstage:input_type -> stage.v1alpha1.NodeUnstageRequest
	1,  // 10: stage.v1alpha1.StagePlugin.PluginInfo:output_type -> stage.v1alpha1.PluginInfoResponse
	6,  // 11: stage.v1alpha1.StagePlugin.NodeStage:output_type -> stage.v1alpha1.NodeStageResponse
	8,  // 12: stage.v1alpha1.StagePlugin.NodeUnstage:output_type -> stage.v1alpha1.NodeUnstageResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_stage_stage_proto_init() }
func file_stage_stage_proto_init() {
	if File_stage_stage_proto != nil {
		return
	}
	file_stage_stage_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeStageRequest_Nvme)(nil),
		(*NodeStageRequest_Device)(nil),
		(*NodeStageRequest_Nfs)(nil),
	}
	file_stage_stage_proto_msgTypes[7].OneofWrappers = []any{
		(*NodeUnstageRequest_Nvme)(nil),
		(*NodeUnstageRequest_Device)(nil),
		(*NodeUnstageRequest_Nfs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stage_stage_proto_rawDesc), len(file_stage_stage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stage_stage_proto_goTypes,
		DependencyIndexes: file_stage_stage_proto_depIdxs,
		MessageInfos:      file_stage_stage_proto_msgTypes,
	}.Build()
	File_stage_stage_proto = out.File
	file_stage_stage_proto_goTypes = nil
	file_stage_stage_proto_depIdxs = nil
}
